streamer_dict = {
    "hljp0": ['AZki', 'Miko', 'Roboco', 'Sora', 'Suisei'],
    "hljp1": ['Mel', 'Haato', 'Fubuki', 'Matsuri', 'Aki'],
    "hljp2": ['Shion', 'Aqua', 'Ayame', 'Choco', 'Subaru'],
    "hljp_g": ['Korone', 'Mio', 'Okayu'],
    "hljp3": ['Noel', 'Rushia', 'Pekora', 'Flare', 'Marine'],
    "hljp4": ['Luna', 'Coco', 'Watame', 'Kanata', 'Towa'],
    "hljp5": ['Lamy', 'Nene', 'Botan', 'Polka'],
    "hlen1": ['Calli', 'Kiara', 'Ina', 'Gura', 'Amelia'],
    "hlid1": ['Risu', 'Moona', 'Iofi'],
    "hlid2": ['Reine', 'Anya', 'Ollie'],
    "hstars1": ['Miyabi', 'Kira', 'Izuru', 'Aruran', 'Rikka'],
    "hstars2": ['Astel', 'Temma', 'Roberu'],
    "hstars3": ['Shien', 'Oga']
}

hljp = streamer_dict['hljp0'] + streamer_dict['hljp1'] + streamer_dict['hljp2'] + streamer_dict['hljp_g'] + streamer_dict['hljp3'] + streamer_dict['hljp4'] + streamer_dict['hljp5']
hlen = streamer_dict['hlen1']
hlid = streamer_dict['hlid1'] + streamer_dict['hlid2']
hstars = streamer_dict['hstars1'] + streamer_dict['hstars2'] + streamer_dict['hstars3']

channel_ids = {
    "AZki": "UC0TXe_LYZ4scaW2XMyi5_kw",
    "Miko": "UC-hM6YJuNYVAmUWxeIr9FeA",
    "Roboco": "UCDqI2jOz0weumE8s7paEk6g", 
    "Sora": "UCp6993wxpyDPHUpavwDFqgg",
    "Suisei": "UC5CwaMl1eIgY8h02uZw7u8A",
    "Mel": "UCD8HOxPs4Xvsm8H0ZxXGiBw",
    "Haato": "UC1CfXB_kRs3C-zaeTG3oGyg",
    "Fubuki": "UCdn5BQ06XqgXoAxIhbqw5Rg",
    "Matsuri": "UCQ0UDLQCjY0rmuxCDE38FGg",
    "Aki": "UCFTLzh12_nrtzqBPsTCqenA",
    "Shion": "UCXTpFs_3PqI41qX2d9tL2Rw",
    "Aqua": "UC1opHUrw8rvnsadT-iGp7Cg",
    "Ayame": "UC7fk0CB07ly8oSl0aqKkqFg",
    "Choco": "UC1suqwovbL1kzsoaZgFZLKg",
    "Subaru": "UCvzGlP9oQwU--Y0r9id_jnA",
    "Korone": "UChAnqc_AY5_I3Px5dig3X1Q",
    "Mio": "UCp-5t9SrOQwXMU7iIjQfARg",
    "Okayu": "UCvaTdHTWBGv3MKj3KVqJVCw",
    "Noel": "UCdyqAaZDKHXg4Ahi7VENThQ",
    "Rushia": "UCl_gCybOJRIgOXw6Qb4qJzQ",
    "Pekora": "UC1DCedRgGHBdm81E1llLhOQ",
    "Flare": "UCvInZx9h3jC2JzsIzoOebWg",
    "Marine": "UCCzUftO8KOVkV4wQG1vkUvg",
    "Luna": "UCa9Y57gfeY0Zro_noHRVrnw",
    "Coco": "UCS9uQI-jC3DE0L4IpXyvr6w",
    "Watame": "UCqm3BQLlJfvkTsX_hvm0UmA",
    "Kanata": "UCZlDXzGoo7d44bwdNObFacg",
    "Towa": "UC1uv2Oq6kNxgATlCiez59hw",
    "Lamy": "UCFKOVgVbGmX65RxO3EtH3iw",
    "Nene": "UCAWSyEs_Io8MtpY3m-zqILA",
    "Botan": "UCUKD-uaobj9jiqB-VXt71mA",
    "Polka": "UCK9V2B22uJYu3N7eR_BT9QA",
    "Calli": "UCL_qhgtOy0dy1Agp8vkySQg",
    "Kiara": "UCHsx4Hqa-1ORjQTh9TYDhww",
    "Ina": "UCMwGHR0BTZuLsmjY_NT5Pwg",
    "Gura": "UCoSrY_IQQVpmIRZ9Xf-y93g",
    "Amelia": "UCyl1z3jo3XHR1riLFKG5UAg",
    "Risu": "UCOyYb1c43VlX9rc_lT6NKQw",
    "Moona": "UCP0BspO_AMEe3aQqqpo89Dg",
    "Iofi": "UCAoy6rzhSf4ydcYjJw3WoVg",
    "Reine": "UChgTyjG-pdNvxxhdsXfHQ5Q",
    "Anya": "UC727SQYUvx5pDDGQpTICNWg",
    "Ollie": "UCYz_5n-uDuChHtLo7My1HnQ",
    "Miyabi": "UC6t3-_N8A6ME1JShZHHqOMw",
    "Kira": "UCEzsociuFqVwgZuMaZqaCsg",
    "Izuru": "UCZgOv3YDEs-ZnZWDYVwJdmA",
    "Aruran": "UCKeAhJvy8zgXWbh9duVjIaQ",
    "Rikka": "UC9mf_ZVpouoILRY9NUIaK-w",
    "Astel": "UCNVEsYbiZjH5QLmGeSgTSzg",
    "Temma": "UCGNI4MENvnsymYjKiZwv9eg",
    "Roberu": "UCANDOlYTJT7N5jlRC3zfzVA",
    "Shien": "UChSvpZYRPh0FvG4SJGSga3g",
    "Oga": "UCwL7dgTxKo8Y4RFIKWaf8gA"
 }